// GENERATED by scripts/bake-chair-placement.mjs -- do not hand-edit.
//
// Chair-body export placement, baked from stubs/chair-body-all-parts.3mf: MakeGood's own Bambu Studio project for the
// complete chair, 12 plates whose part orientations, plate packing and per-part print
// overrides were checked in the slicer by a human. Same rule as FOOTREST_PLATE_R and WHEEL_TOP_POS
// in threemf.ts -- these numbers come from a file someone verified, and are never re-derived per
// printer or recomputed at export time.
//
// Keyed by library part id (not role id) because the caster roles resolve to a different mesh per
// hardware variant, and Standard and Kit sit on different plates.
//
//   plateR    the reference <item transform>'s rotation, verbatim (noise snapped to exact 0/+-1).
//             Overrides the default face-down tilt, so nsign/rotZdeg do not apply.
//   fixedPos  the matching translation, moved into the app's assembled-chair mesh frame
//             (t_item - source_offset * plateR) and made plate-local. Applied verbatim on a
//             256x256 plate -- the plate the reference was authored on -- and re-centered per
//             plate group on any other bed size by placeHintedGroup.
//   plateHint 1-based reference plate. Values are not contiguous: one caster variant is active at
//             a time, so a real export skips whichever caster plate is unused.
//   primeTowerDelta
//             where that plate's prime tower goes, as an offset from this part's placed
//             translation. Baked from four-filament exports with every plate's tower dragged into
//             place in the slicer and saved back, because the placement reference above prints in
//             one or two filaments and never had a real tower on it:
//               stubs/chair-tower-reference-snapmaker.3mf  (default)
//               stubs/chair-tower-reference-a1.3mf
//             Held relative, not as a bed coordinate: a different bed re-centers each plate's
//             group, and the tower has to travel with the part it was checked against. Present on
//             exactly one part per plate (the plate's anchor); 2 plate(s) have none and fall
//             back to threemf.ts's suggestTowerPos.
//   primeTowerDeltaByPlate
//             a bed size where that transfer did not hold and the tower had to be re-checked, keyed
//             "<w>x<d>". Verified beds: 270x270, 256x256. Only the plates that actually
//             disagreed carry a key -- one that merely restated the default would bury the ones
//             that matter. Any other bed size uses primeTowerDelta and is unverified.
//
// Z is deliberately absent: every part rests flat on the plate in the reference (verified minZ 0),
// so build3MFCombined's tz = -minZ reproduces it exactly.
//
// Regenerate (needs both files above, neither of which is in the repo):
//   npx vite-node scripts/bake-chair-placement.mjs
// It re-verifies every shipped mesh against the reference before writing; the worst plate-space
// bounding-box disagreement at the last bake was 0.024mm.

export interface ChairPartPlacement {
  plateHint: number;
  plateR: number[][];
  fixedPos: { x: number; y: number };
  primeTowerDelta?: { x: number; y: number };
  primeTowerDeltaByPlate?: Record<string, { x: number; y: number }>;
  objectSettings?: Record<string, string>;
}

export const CHAIR_PLACEMENT: Record<string, ChairPartPlacement> = {
  'chair-handle-left': {
    plateHint: 1,
    plateR: [
      [1, 0, 0],
      [0, -0.309017, 0.951057],
      [0, -0.951057, -0.309017],
    ],
    fixedPos: { x: 37.129322, y: -228.677691 },
    primeTowerDelta: { x: 26.0354, y: 422.860564 },
    primeTowerDeltaByPlate: {
      '256x256': { x: 26.035399, y: 421.703549 },
    },
    objectSettings: { brim_type: 'outer_only', brim_width: '10', support_type: 'tree(manual)' },
  },
  'chair-handle-right': {
    plateHint: 2,
    plateR: [
      [1, 0, 0],
      [0, -0.309017, 0.951056],
      [0, -0.951056, -0.309017],
    ],
    fixedPos: { x: 224.790702, y: -231.111611 },
    primeTowerDelta: { x: -80.543, y: 417.39205 },
    objectSettings: { brim_type: 'outer_only', brim_width: '10', support_type: 'tree(manual)' },
  },
  'chair-wheel-mount-left': {
    plateHint: 3,
    plateR: [
      [0, 0, -1],
      [1, 0, 0],
      [0, -1, 0],
    ],
    fixedPos: { x: -93.378462, y: -200.828289 },
    primeTowerDelta: { x: 311.364351, y: 234.615952 },
    primeTowerDeltaByPlate: {
      '256x256': { x: 309.607351, y: 235.067352 },
    },
    objectSettings: { support_type: 'tree(manual)', support_style: 'tree_hybrid' },
  },
  'chair-wheel-mount-right': {
    plateHint: 4,
    plateR: [
      [0, 0, 1],
      [-1, 0, 0],
      [0, -1, 0],
    ],
    fixedPos: { x: 362.880432, y: -199.133999 },
    primeTowerDelta: { x: -346.57925, y: 239.146452 },
    primeTowerDeltaByPlate: {
      '256x256': { x: -347.08445, y: 235.252352 },
    },
    objectSettings: { support_type: 'tree(manual)', support_style: 'tree_hybrid' },
  },
  'chair-wing-right': {
    plateHint: 5,
    plateR: [
      [0, 0, -1],
      [-0.175808, 0.984425, 0],
      [0.984425, 0.175808, 0],
    ],
    fixedPos: { x: 271.814541, y: 9.294586 },
    primeTowerDelta: { x: -74.02334, y: 188.789981 },
  },
  'chair-wing-left': {
    plateHint: 6,
    plateR: [
      [0, 0, 1],
      [0.986264, -0.165175, 0],
      [0.165175, 0.986264, 0],
    ],
    fixedPos: { x: 8.402164, y: 270.441311 },
    primeTowerDelta: { x: 185.223175, y: -70.639791 },
  },
  'chair-storage-right': {
    plateHint: 7,
    plateR: [
      [0, 0, 1],
      [0, -1, 0],
      [1, 0, 0],
    ],
    fixedPos: { x: 662.534902, y: 336.733949 },
    primeTowerDelta: { x: -620.6281, y: -268.164034 },
    objectSettings: { support_type: 'tree(manual)', support_style: 'tree_hybrid' },
  },
  'chair-storage-left': {
    plateHint: 8,
    plateR: [
      [0, 0, -1],
      [-1, 0, 0],
      [0, 1, 0],
    ],
    fixedPos: { x: 335.539799, y: 663.055622 },
    primeTowerDelta: { x: -272.04993, y: -619.1091 },
    objectSettings: { support_type: 'tree(manual)', support_style: 'tree_hybrid' },
  },
  'chair-caster-std-left': {
    plateHint: 9,
    plateR: [
      [0, 0, -1],
      [0, 1, 0],
      [1, 0, 0],
    ],
    fixedPos: { x: 695.839768, y: -63.731257 },
    objectSettings: {
      sparse_infill_density: '20%',
      skin_infill_density: '20%',
      skeleton_infill_density: '20%',
      wall_loops: '4',
    },
  },
  'chair-caster-std-right': {
    plateHint: 9,
    plateR: [
      [0, 0, 1],
      [0, -1, 0],
      [1, 0, 0],
    ],
    fixedPos: { x: 696.204738, y: 315.889437 },
    objectSettings: {
      sparse_infill_density: '20%',
      skin_infill_density: '20%',
      skeleton_infill_density: '20%',
      wall_loops: '4',
    },
  },
  'chair-caster-kit-left': {
    plateHint: 10,
    plateR: [
      [0, 0, -1],
      [0, 1, 0],
      [1, 0, 0],
    ],
    fixedPos: { x: 692.727278, y: -57.248257 },
    objectSettings: {
      sparse_infill_density: '20%',
      skin_infill_density: '20%',
      skeleton_infill_density: '20%',
      wall_loops: '4',
    },
  },
  'chair-caster-kit-right': {
    plateHint: 10,
    plateR: [
      [0, 0, 1],
      [0, -1, 0],
      [1, 0, 0],
    ],
    fixedPos: { x: 691.562278, y: 319.666788 },
    objectSettings: {
      sparse_infill_density: '20%',
      skin_infill_density: '20%',
      skeleton_infill_density: '20%',
      wall_loops: '4',
    },
  },
  'chair-seat-back-bottom': {
    plateHint: 11,
    plateR: [
      [0, 0, 1],
      [1, 0, 0],
      [0, 1, 0],
    ],
    fixedPos: { x: -143.72495, y: 610.342517 },
    primeTowerDelta: { x: 186.3075, y: -452.192074 },
  },
  'chair-seat-back-top': {
    plateHint: 11,
    plateR: [
      [0, 0, 1],
      [0.999202, 0.039938, 0],
      [-0.039938, 0.999202, 0],
    ],
    fixedPos: { x: -350.157609, y: 525.231697 },
  },
  'chair-seat-center': {
    plateHint: 12,
    plateR: [
      [0, 0, -1],
      [0.707107, 0.707107, 0],
      [0.707107, -0.707107, 0],
    ],
    fixedPos: { x: 223.829541, y: -285.138799 },
    primeTowerDelta: { x: -121.971385, y: 469.969233 },
    objectSettings: { support_type: 'tree(manual)' },
  },
};
