// GENERATED by scripts/bake-part-fingerprints.mjs -- do not hand-edit.
//
// One mesh fingerprint (triangle count + bbox hash, src/geometry/zoneCharts.ts meshFingerprint)
// per public/stl/parts.json entry, sealing the mesh src/export/placement.ts's baked plateR/
// fixedPos/primeTowerDelta/objectSettings were verified against. A part whose loaded mesh doesn't
// match its seal here loses its baked placement rather than having it silently misapplied — see
// resolvePlacement in src/export/placement.ts.
//
// Sealing is "same mesh file", not "same part": a CAD re-export of the identical part at a
// different triangle count fails this seal even though its orientation/extents (and so plateR)
// would still be correct. That's deliberate -- a looser check would be a second, weaker
// verification method living next to zoneCharts.ts's, and re-packing a part already means
// re-verifying its placement in the slicer, which is the moment to reseal too.
//
// Regenerate: npx vite-node scripts/bake-part-fingerprints.mjs

export const PART_FINGERPRINTS: Record<string, { triangleCount: number; bboxHash: string }> = {
  'chair-caster-kit-left': { triangleCount: 8504, bboxHash: '2d2d039d' },
  'chair-caster-kit-right': { triangleCount: 8468, bboxHash: 'bfba70d3' },
  'chair-caster-std-left': { triangleCount: 8434, bboxHash: 'f7908ea1' },
  'chair-caster-std-right': { triangleCount: 8396, bboxHash: '9b81710f' },
  'chair-handle-left': { triangleCount: 46318, bboxHash: '3ca7470b' },
  'chair-handle-right': { triangleCount: 46466, bboxHash: '25d2a7cd' },
  'chair-seat-back-bottom': { triangleCount: 14560, bboxHash: '04ece6bd' },
  'chair-seat-back-top': { triangleCount: 18394, bboxHash: 'd4e500bf' },
  'chair-seat-center': { triangleCount: 18716, bboxHash: '79364c6a' },
  'chair-storage-left': { triangleCount: 46494, bboxHash: 'be4a9352' },
  'chair-storage-right': { triangleCount: 42646, bboxHash: '4f32a3f1' },
  'chair-wheel-mount-left': { triangleCount: 24882, bboxHash: 'd6d43df6' },
  'chair-wheel-mount-right': { triangleCount: 25382, bboxHash: 'a99a8574' },
  'chair-wing-left': { triangleCount: 37820, bboxHash: '24c53044' },
  'chair-wing-right': { triangleCount: 29822, bboxHash: '00aa6d07' },
  footrest: { triangleCount: 10772, bboxHash: 'c4dcb701' },
  'wheel-half': { triangleCount: 17968, bboxHash: 'ff17faa8' },
  'wheel-hub-cap': { triangleCount: 8994, bboxHash: 'f2bbf403' },
};
