import JSZip from 'jszip';
import { baseColorHex, state } from '../state/store';
import { nearestFilamentName } from '../state/filaments';
import { getLastAssemblyBuild, getLastBuild } from '../app/rebuild';
import { asmPartFaceNormal } from '../geometry/assembly';
import { build3MFCombined, type ExportMaterial, type ExportPart } from '../export/threemf';
import { meshToSTLBlob, soupFromObject } from '../export/stl';
import { hideOverlay, showOverlay } from './overlay';
import { $ } from './dom';

function download(blob: Blob, fname: string): void {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fname;
  a.click();
}

async function exportPrintReady3MF(): Promise<void> {
  let materials: ExportMaterial[], parts: ExportPart[], fname: string;
  const bodyColor = baseColorHex().toUpperCase();

  if (state.shapeKind === 'assembly') {
    const built = getLastAssemblyBuild();
    if (!built || !built.partOutputs.length) return;
    const palette = built.palette;
    materials = [{ name: 'Body', color: bodyColor }].concat(
      palette.map((p) => ({ name: nearestFilamentName(p.hex), color: p.hex })),
    );
    parts = built.partOutputs
      .filter((o) => o.bodySoup && o.bodySoup.length)
      .map(({ part, bodySoup, inlaySoups }) => {
        const nrm = asmPartFaceNormal(part, state.assembly.parts);
        const nsign = nrm && nrm[1] < 0 ? -1 : 1;
        const subs = [{ name: 'Body', matIndex: 0, soup: bodySoup }];
        Object.entries(inlaySoups).forEach(([ci, soup]) => {
          subs.push({ name: nearestFilamentName(palette[+ci].hex), matIndex: +ci + 1, soup });
        });
        return { name: part.name, nsign, bodySoup, subs };
      });
    fname = 'mosaic-wheel.3mf';
  } else {
    const built = getLastBuild();
    if (!built) return;
    // flat-plate mode: the already-built slab-stack body + per-color plugs become one
    // multi-part object. nsign 0 = exported upright, no face-down tilt — the design face
    // is already +Z and the underside already sits at Z=0.
    materials = [{ name: 'Body', color: bodyColor }].concat(
      built.colorMeshes.map((c) => ({
        name: c.isBackground ? 'Background' : nearestFilamentName(c.color),
        color: c.color,
      })),
    );
    const bodySoup = soupFromObject(built.baseGroup);
    const subs = [{ name: 'Body', matIndex: 0, soup: bodySoup }].concat(
      built.colorMeshes.map((c, i) => ({
        name: materials[i + 1].name,
        matIndex: i + 1,
        soup: soupFromObject(c.mesh),
      })),
    );
    parts = [{ name: 'Mosaic plate', nsign: 0, bodySoup, subs }];
    fname = 'mosaic-plate.3mf';
  }

  showOverlay('Exporting print-ready 3MF…');
  await new Promise((r) => setTimeout(r, 10));
  try {
    // No Z spin: the unrotated footprint is the smallest bbox for the half-disc tops, which is
    // what lets the cap share a plate when the plate is wide enough.
    const [pw, pd] = (state.plateSize || '256x256').split('x').map(Number);
    const blob = await build3MFCombined(materials, parts, { rotZdeg: 0, plate: { w: pw, d: pd } });
    download(blob, fname);
  } catch (e) {
    console.error(e);
    alert('Export failed: ' + (e as Error).message);
  }
  hideOverlay();
}

async function exportSTLSet(): Promise<void> {
  const built = getLastBuild();
  if (!built) return;
  showOverlay('Exporting STL set…');
  await new Promise((r) => setTimeout(r, 10));
  try {
    const zip = new JSZip();
    zip.file('base.stl', meshToSTLBlob(built.baseGroup));
    built.colorMeshes.forEach((c, idx) => {
      let label: string;
      if (c.isBackground) label = 'background';
      else if (c.isMergeGroup)
        label = 'merged_' + c.members.map((h) => h.replace('#', '')).join('+');
      else label = c.color.replace('#', '');
      zip.file(`color_${String(idx + 1).padStart(2, '0')}_${label}.stl`, meshToSTLBlob(c.mesh));
    });
    const readme = `Mosaic for TMT export
======================
${built.colorMeshes.length} color STL(s) + base.stl (uncut plate body).

Bambu Studio workflow:
1. File > Import > import all STLs from this folder as separate objects.
2. Select all imported objects, right-click > "Assemble" (or drag them onto one another) so they share one build plate position and register as one multi-part object.
3. In the object list, click each part and assign it a filament / AMS slot from the color swatch.
4. Slice as normal — Bambu Studio will generate the per-color toolpaths and AMS color changes automatically.

Generated by TMT Mosaic, a MakeGood tool for the Toddler Mobility Trainer
(TMT) — makegood.design / 3d-mobility.org. A browser-based tool, not
affiliated with Bambu Lab.
`;
    zip.file('README.txt', readme);
    const blob = await zip.generateAsync({ type: 'blob' });
    download(blob, 'mosaic-export.zip');
  } catch (e) {
    console.error(e);
    alert('Export failed: ' + (e as Error).message);
  }
  hideOverlay();
}

export function initExportPanel(): void {
  $<HTMLSelectElement>('#p-plate-size').addEventListener('change', (e) => {
    state.plateSize = (e.target as HTMLSelectElement).value;
  });
  $('#btn-export').addEventListener('click', () => void exportPrintReady3MF());
  $('#btn-export-stl').addEventListener('click', () => void exportSTLSet());
}
